Trie
skuzi/JavaHW pull request #2
Opened 2019-02-05 21:16 UTC by skuzi

first try.

2019-02-08 17:23 UTC, RamSaw requested changes
@skuzi, домашку проверил. Как пофиксите или напишите контраргументы (не стесняйтесь спорить аргументированно, я тоже могу ошибаться), упомяните меня через "@RamSaw". У меня, к сожалению, доступа к hwproj нет, поэтому так поступим. Но если увижу на hwproj, что Вы пофиксили, то тоже посмотрю.
Вообще Ваше решение очень похоже на https://github.com/lyubortk/HSE-java-HW/pull/2 и отправили Вы его сильно позже Константина. Насколько сильно Вы изучали его код?

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +public class Trie {
Выделите пожалуйста интерфейс Serializable, в задании это явно сказано. Дело в том, что этот интерфейс могут захотеть реализовывать не только вы, к примеру, для того чтобы потом отправить эти данные по сети методом send(Serializable obj). Полиморфизм наше все.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        root = new TrieNode();
Можно сразу в объявлении поля присваивать.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +     * @param element the string which is added, mustn't be <code>null</code>
`mustn't be <code>null</code>`, не думаю, что есть смысл везде это писать, у вас же аннотация там и так весит.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        private TrieNode getNext(char c) {
комментарий и название функции как-то не очень коррелируют. Первоочередной смысл метода дать новую ноду, а если нет создать. А у Вас в комментарии только про создать.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        /** Makes this node terminal (only if it was not terminal).
Напишите тогда уж в комментариях, что метод нельзя вызывать на терминальных вершинах, а не `only if it was not terminal`. Вообще к приватным методом javadoc можно не писать.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        /** Makes this node not terminal (only if it was terminal).
Напишите тогда уж в комментариях, что метод нельзя вызывать на нетерминальных вершинах, а не `only if it was terminal`. Вообще к приватным методом javadoc можно не писать.
И многострочные javadoc'и пишутся так:
`/**`
` * data1`
` * data2`
` */`

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
try with resources лучше здесь использовать.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        var dataIn = new DataInputStream(in);
Тоже самое про try with resources.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +    Trie trie;
Сделайте приватным поле и уберите сверху пустую строку, пожалуйста.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +        assertTrue(trie.contains(String.valueOf(50)));
Можно уж проверить что все 100 содержит, строчек столько же будет.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +        String words[] = {"a", "abacaba", "abcabc", "bc", "abcbac", "adbcc", "abac", "acc"};
String[] words, а не String words[].

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +        assertEquals(trie.size(), getter.size());
Давайте перегрузим equals у Trie (и hashCode тоже), а здесь просто напишем assertEquals(trie, getter). Так мы как можно более полно проверим, что они действительно равны. Следующих тестов тоже касается.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +    void serializeEmpty() {
Протестируйте, пожалуйста, что serialize и deserialize корректно работают по отдельности. То есть это будет тестирование протокола, согласно которому вы сериализуете.

2019-02-08 17:23 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +
Зачем здесь пустая строка?

2019-02-13 23:52 UTC, skuzi commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
Почитал про это какую-то информацию и нашел, что закрытие внутреннего потока также закроет и внешний поток, от которого мы сконструировались. Кажется, что не очень хочется закрывать поток, который нам передали извне, и который еще может как-то использоваться пользователем. Поэтому не стал писать try with resources и убрал `dataOut.close()`

2019-02-13 23:55 UTC, skuzi commented
@RamSaw пофиксил, что было, кроме try with resources, о чем написал в комменте. 
Код Кости я смотрел, мне понравилась идея с нерекурсивным бором, решил написать так же, но, насколько я помню, изучал не сильно.
Хотелось бы также спросить про интерфейс `Serializable`. Почему-то в официальных доках сказано, что класс, реализующий этот интерфейс, должен реализовывать три каких-то метода, но в самом коде (по крайней мере в идее), этот интерфейс пустой. Как так вышло?

2019-02-17 21:44 UTC, RamSaw requested changes
Про интерфейс Serializable: есть стандартный метод сериализации, которым вам тут запретили пользоваться - ObjectOutputStream.writeObject(Object). 
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/ObjectOutputStream.html
тут последний ответ неплохой - https://stackoverflow.com/questions/15338720/the-class-which-implements-serializable-needs-to-impliment-some-methods
Собственно надо implements Serializable, чтобы если Ваш объект хранится как поле, то он смог бы сериализоваться. А если в тупую его сериализовать нельзя, то надо переопределить эти методы, чтобы были ваши алгоритмы сериализации.

2019-02-17 21:44 UTC, RamSaw commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +    private boolean subtreeEquals(TrieNode node1, TrieNode node2) {
Вы опять смотрели к Константину? Сходите, пожалуйста, тогда к нему в Pull Request и исправьте все замечания, которые я ему написал и которые тоже Вас касаются. Потом упомяните меня, я посмотрю. Но прошу Вас больше к нему не смотреть.

2019-02-17 23:00 UTC, skuzi commented
@RamSaw добавил try-with-resources и методы от идеи. 

Мой вопрос про Serializable был скорее связан не с этим. Я понимаю, что если сериализовывать по-умному, то надо будет реализовывать эти методы. Но методы, которые предложено реализовывать в задании, отличаются, поэтому я не понял, как это связано с writeObject и readObject. Логичнее было бы попросить перегрузить их, или я в чем-то не прав?

2019-02-21 18:09 UTC, RamSaw requested changes
Пофиксите последнее замечание, пожалуйста.

2019-02-21 18:09 UTC, RamSaw commented on trie/src/test/java/ru/hse/kuzyaka/trie/TrieTest.java
> +            System.out.println("Something went wrong with moving data, probable reason is:");
Если в тесте что-то пошло не так, то он должен падать. Поставьте тогда у теста throws IOException и уберите этот catch. Ниже соответсвенно тоже самое.

2019-02-21 19:02 UTC, RamSaw requested changes
Кажется catch все еще остался в тестах...
И у вас конфликты в gitignore, пофиксите, пожалуйста.

2019-02-21 19:38 UTC, skuzi commented
@RamSaw вроде пофиксил, но почему-то не уверен...

2019-02-21 19:55 UTC, RamSaw approved these changes
Ок. Передаю слово @jzuken .

2019-03-07 10:53 UTC, jzuken requested changes

2019-03-07 10:53 UTC, jzuken commented on trie/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
лучше всё же пятый использовать

2019-03-07 10:53 UTC, jzuken commented on trie/src/main/java/ru/hse/kuzyaka/trie/Serializable.java
> +     * @throws IOException
и где описание? не надо таких подвешенных тегов оставлять
-0.5

2019-03-07 10:53 UTC, jzuken commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +    /**
все однострочные доки лучше писать в одну строчку

2019-03-07 10:53 UTC, jzuken commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +        private HashMap<Character, TrieNode> next;
не самое удачное имя. называется next, а внезапно там ассоциативный массив

2019-03-07 10:53 UTC, jzuken commented on trie/src/main/java/ru/hse/kuzyaka/trie/Trie.java
> +            var curNode = this;
лучше не надо таких сокращений в коде
-0.5

2019-03-13 14:15 UTC, jzuken requested changes

2019-03-13 14:15 UTC, jzuken commented on trie/src/main/java/ru/hse/kuzyaka/trie/Serializable.java
> +     * @throws IOException
всё ещё висящий тег без документации :(
-1

2019-03-16 14:21 UTC, merged