Mytreeset
skuzi/JavaHW pull request #3
Opened 2019-02-13 19:02 UTC by skuzi

first try.

2019-03-07 09:41 UTC, jzuken commented
конфликт с мастером

2019-03-07 09:50 UTC, jzuken requested changes

2019-03-07 09:50 UTC, jzuken commented on hashtable/src/main/java/ru/hse/kuzmins/hashtable/HashTable.java
> -package ru.hse.kuzmins.hashtable;
и все эти замечательные проблемы тут оттого, что вы отвели ветку не от мастера, а от задачи 1. и вместо того, чтобы переложить коммиты и сделать всё хорошо, вы зачем-то удалили просто этот код. и что будет, если я это в мастер замержу?

-1

2019-03-07 09:50 UTC, jzuken commented on mytreeset/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
четвёртый gradle не умеет с 11 джавой работать

2019-03-07 09:50 UTC, jzuken commented on mytreeset/src/main/java/ru/hse/kuzyaka/mytreeset/Treap.java
> +            if(this.version != Treap.this.version) {
пробел. тут и дальше

2019-03-13 14:40 UTC, skuzi commented
Не уверен, что пофиксил проблемы с гитом, наверно, опыта не особо хватает. Но локально все вроде хорошо замержилось после того, как вернул hashtable.

2019-03-16 14:37 UTC, jzuken commented
вот чтобы опыт появился, надо сделать так, как я просил. в изменённых файлах пуллреквеста всё равно фигня отображается

2019-03-21 16:52 UTC, closed without merging