Database
skuzi/JavaHW pull request #4
Opened 2019-02-26 23:32 UTC by skuzi

first try

2019-02-27 00:27 UTC, skuzi commented
тесты падают с MongoTimeoutException, не очень понял, почему, локально все работает =(

2019-03-16 14:19 UTC, jzuken requested changes

2019-03-16 14:19 UTC, jzuken commented on database/src/test/java/ru/hse/kuzyaka/phonebook/PhoneBookTest.java
> +    private PhoneBook phoneBook = new PhoneBook();
то есть тесты хреначат в ту же базу, что и боевое приложение, каждый раз её перетирая? не делайте так больше никогда
-1

2019-03-16 14:19 UTC, jzuken commented on database/src/main/java/ru/hse/kuzyaka/phonebook/Main.java
> +        System.out.println("ENTER COMMAND CODE:");
ну, хорошо бы пользователю показать возможные варианты

2019-03-16 14:19 UTC, jzuken commented on database/src/main/java/ru/hse/kuzyaka/phonebook/Main.java
> +                    phoneBook.getNumbersByPerson(name).stream().
а на несуществующем имени оно валится с NPE. добавьте везде обработку нестандартных ситуаций, пожалуйста
-1

2019-03-21 19:32 UTC, jzuken commented
с тестами вы так и не разобрались, поэтому 7 баллов

2019-05-19 19:58 UTC, closed without merging