Reflector
skuzi/JavaHW pull request #5
Opened 2019-03-13 21:01 UTC by skuzi

на винде почему-то не работает, но в тревисе вроде проходит тесты

2019-03-18 17:03 UTC, jzuken commented
где на тревисе проходит? 

ru.hse.kuzyaka.reflector.ReflectorTest > testPrintFields() FAILED
    org.opentest4j.AssertionFailedError at ReflectorTest.java:253
ru.hse.kuzyaka.reflector.ReflectorTest > testInnerGeneric() FAILED
    org.opentest4j.AssertionFailedError at ReflectorTest.java:253
8 tests completed, 2 failed

-1

2019-03-18 17:04 UTC, jzuken commented
под виндами какие-то тесты не проходят потому, что вы захардкодили символ перевода строки, а лучше использовать System.lineSeparator()

2019-03-18 17:09 UTC, jzuken requested changes

2019-03-18 17:09 UTC, jzuken commented on reflector/src/test/java/ru/hse/kuzyaka/reflector/ReflectorTest.java
> +                "    }\n" +
и пока вы это всё отчаянно форматировали, у вас не возникло мысли, что можно просто из файла прочитать?

2019-03-18 17:09 UTC, jzuken commented on reflector/src/test/java/ru/hse/kuzyaka/reflector/testclasses/Generic1Copy.java
> +public class Generic1Copy<T, E extends List<T>> {
интерфейсы бы ещё проверить

2019-03-18 17:09 UTC, jzuken commented on reflector/src/main/java/ru/hse/kuzyaka/reflector/Reflector.java
> +        return differentMethods(secondClass, firstClass, writer) |
вообще это побитовая операция, а вам нужна логическая

2019-03-18 17:09 UTC, jzuken commented on reflector/src/test/java/ru/hse/kuzyaka/reflector/ReflectorTest.java
> +class ReflectorTest {
а где тест на компиляцию?
-2

2019-03-21 18:32 UTC, skuzi commented
Не очень понял, почему не работают тесты на компиляцию -- складывается ощущение, что сначала компилятор пытается компилировать несуществующий файл (или существующий, но с другим содержимым), а затем уже пишется содержимое, которое должно там лежать по факту

2019-03-21 19:43 UTC, jzuken commented
ну, было бы неплохо с вашей стороны всё же разобраться, что не так с тестами
5 баллов

2019-03-21 19:43 UTC, merged